FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --default-timeout=1000 --no-cache-dir -r requirements.txt

COPY backend/ backend/
COPY ml/ ml/

RUN mkdir -p backend/checkpoints

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
